import type { Metadata } from "next";
import { Signika_Negative,Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer/page";
import NavBar from "./components/navbar/page";

const signika = Signika_Negative({ subsets: ["latin"] });
const grotesk = Space_Grotesk({subsets: ["latin"]})
const inter = Inter({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Future Alied",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={signika.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
